kind: pipeline
name: default
type: kubernetes

node_selector:
  kubernetes.io/arch: arm64

steps:
- name: test
  image: alpine:3.18
  pull: true
  commands:
  - apk --no-cache add python3 py3-pip py3-psycopg2 postgresql-client
  - pip3 install -r test/requirements.txt
  - python3 test/manage.py migrate damt 0002
  - sh -c "python3 test/manage.py migrate damt & python3 test/manage.py migrate damt ; true"
  - sh -c "test $(psql -tA postgresql://damt:damt@postgres:5432/damt?sslmode=disable -c 'select value from damt_testmodel') -eq 2"

- name: publish
  image: alpine:3.18
  commands:
  - apk --no-cache add python3 py3-pip py3-twine py3-colorama
  - pip3 install rfc3986
  - python3 setup.py sdist
  - twine upload dist/*
  environment:
    TWINE_USERNAME: __token__
    TWINE_PASSWORD:
      from_secret: pypi_password
  when:
    event:
    - tag

services:
- name: postgres
  image: postgres
  environment:
    POSTGRES_USER: damt
    POSTGRES_PASSWORD: damt
