kind: pipeline
name: default

platform:
  os: linux
  arch: arm

steps:
- name: test
  image: alpine:3.10
  pull: true
  commands:
  - apk --no-cache add python3 py3-psycopg2 postgresql-client
  - pip3 install -U pip -r test/requirements.txt
  - python3 test/manage.py migrate damt 0002
  - sh -c "python3 test/manage.py migrate damt & python3 test/manage.py migrate damt ; true"
  - sh -c "test $(psql -tA postgresql://damt:damt@postgres:5432/damt?sslmode=disable -c 'select value from damt_testmodel') -eq 2"

- name: publish
  image: alpine:3.10
  commands:
  - apk --no-cache add python3 git
  - git fetch --tags
  - pip3 install twine
  - python3 setup.py sdist
  - python3 -m twine upload dist/*
  environment:
    TWINE_USERNAME: rkojedzinszky
    TWINE_PASSWORD:
      from_secret: pypi_password
  when:
    event:
    - tag

services:
- name: postgres
  image: postgres
  environment:
    POSTGRES_USER: damt
    POSTGRES_PASSWORD: damt
