# Generated by Django 2.2.6 on 2019-10-07 18:46

from django.db import migrations

def fill(apps, schema_editor):
    Testmodel = apps.get_model('damt', 'Testmodel')
    Testmodel.objects.create(id=1, value=1)


class Migration(migrations.Migration):

    dependencies = [
        ('damt', '0001_initial'),
    ]

    operations = [
            migrations.RunPython(fill),
    ]
