# Generated by Django 2.2.6 on 2019-10-07 18:48

from django.db import migrations
import time


def incre(apps, schema_editor):
    Testmodel = apps.get_model('damt', 'Testmodel')

    time.sleep(2)
    m = Testmodel.objects.select_for_update().get(pk=1)
    m.value += 1
    m.save()


class Migration(migrations.Migration):

    dependencies = [
        ('damt', '0002_fill'),
    ]

    operations = [
            migrations.RunPython(incre),
    ]
